name: Build and Deploy
on: 
  push:
      branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          # 选择要使用的 node 版本
          node-version: '14'

    - name: vuepress-deploy
      uses: actions/setup-node@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: docs/.vuepress/dist
